### ISSUE TITLE
OAuth middleware doesn't respect CURL settings or custom HTTP client

### ISSUE THREAD

**Issue by Synergy-ek** [plokko/firebase-php#11]
In case of using CURL with proxy or IP binding, options doesn't pushed to OAuth2 middleware.
If set, custom HTTP client should be posted to CredentialsLoader::makeHttpClient() at src/ServiceAccount.php, line 69

**Comment by marianoarga** [comment]
Looking forward to know about using this library with a proxy

**Comment by plokko** [comment]
The FCM Request class do support custom a GuzzleHttp client
```php
//Custom http client
$myClient = new Client(['debug'=>true]);
$request->setHttpClient($myClient);
```
The ServiceAccount should contain only the service account informations, connection options should be set on the calling class (in this example the FCM request that can authorize the request with a custom client)
