### ISSUE TITLE
Multiline or HTML Body

### ISSUE THREAD

**Issue by kurtc** [plokko/firebase-php#20]
Is it possible to include multiple lines or HTML in the content body.

$message->notification
            ->setTitle('Notification title')
            ->setBody('firstLine\nSecond Line');

OR 

$message->notification
            ->setTitle('Notification title')
            ->setBody('firstLine<br>second Line');

Any insight to the possibilities and limitation would be appreciated. thanks

**Comment by plokko** [comment]
The library simply interfaces with Firebase API, please do test if it's a Firebase limitatio  before opening an issue.
Thank you
