### ISSUE TITLE
Condition in Message

### ISSUE THREAD

**Issue by marianoarga** [plokko/firebase-php#3]
Hello, how can I create a message that reaches all users in app?, inside FCM console you can use a "condition", wich I see is present in this library, but is seems not no be aplied in "Plokko\Firebase\FCM\Message.php" as a possible Target.

**Comment by plokko** [comment]
Condition should be a valid Message target, see example in docs:
```php
use Plokko\Firebase\FCM\Targets\Condition; //Be sure you're using the right class!
//...
$message->setTarget(new Condition('your-fcm-conditions'));
```
**Note:** all targets needs to extend  ```Plokko\Firebase\FCM\Targets\Target```
