### ISSUE TITLE
Apns config does not work

### ISSUE THREAD

**Issue by Juanperezc** [plokko/firebase-php#9]
Hi, I'm trying the apn settings to set the thread-id, since I need notifications to be repeated, or replaced with an existing one

https://stackoverflow.com/questions/49758268/can-you-set-thread-id-with-fcm-nottoos-for-ios

But I can not set this configuration, I'm doing it in the following way

` $message->apns->payload->aps->thread_id = "example";`

and I do not get an error but it does not work either

**Comment by Juanperezc** [comment]
I am doing it in the following way

```
$message->apns->payload->aps->alert = "Hello World!";
        $message->apns->payload->aps->sound = "default";
        $message->apns->payload->aps->category = "example-category";
        $message->apns->payload->aps->thread_id = $this->type;
```


The weird thing is that the alert works for me and I think the others but the thread-id does not

**Comment by plokko** [comment]
I do not know APNS funcionality and i don't even have apple products to test with it, please dump the full json message payload (before submission) so i can confront it with the documentation like this and post it here:
```php
exit(json_encode($message,JSON_PRETTY_PRINT));
```
